"""
server.py — HTTP Gateway + ngrok + XML Builder API
====================================================
Runs the Vobiz webhook handler and the stream application builder API.

What this does:
  - Exposes /answer, /hangup, /stream-status webhooks for Vobiz
  - Runs the XML builder API at /api/applications/stream
  - Serves the frontend UI at /ui (or open index.html directly)
  - Optionally creates an ngrok tunnel for public access

What this does NOT do:
  - Does NOT run an AI agent
  - Does NOT require OpenAI or Deepgram keys
  - Does NOT proxy WebSocket traffic to an agent

If you want the full AI voice agent, see the agent/ folder.
"""

import os
import sys
import logging
import uvicorn

from fastapi import FastAPI, Request
from fastapi.responses import Response, FileResponse
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv
from pyngrok import ngrok, conf

load_dotenv()

from xml_builder import router as xml_builder_router  # noqa: E402

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
HTTP_PORT       = int(os.getenv("HTTP_PORT", "8000"))
NGROK_AUTH_TOKEN = os.getenv("NGROK_AUTH_TOKEN", "")

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("server")

# ---------------------------------------------------------------------------
# FastAPI App
# ---------------------------------------------------------------------------
app = FastAPI(title="Vobiz Stream Application Builder")

# CORS — allows the S3-hosted or locally-opened index.html to call this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # tighten to your S3 bucket URL in production
    allow_methods=["*"],
    allow_headers=["*"],
)

# XML builder routes: /api/applications/stream, /api/applications/{id}, etc.
app.include_router(xml_builder_router)

# Global — set after ngrok starts (or set to localhost in local mode)
NGROK_URL = None


# ---------------------------------------------------------------------------
# Vobiz Webhook Routes
# ---------------------------------------------------------------------------

@app.get("/")
async def serve_ui():
    """Serve the builder UI at http://localhost:8000/"""
    return FileResponse(os.path.join(os.path.dirname(__file__), "index.html"))


@app.post("/answer")
async def answer_call(request: Request):
    """
    Vobiz calls this when a call connects.
    In this server (XML builder mode), the answer_url is the S3/local XML URL
    generated by the builder — Vobiz fetches it directly.

    This /answer endpoint is still here as a fallback for manual testing,
    but in production the answer_url points to the generated XML, not here.
    """
    form_data = await request.form()
    call_uuid    = form_data.get("CallUUID", "unknown")
    from_number  = form_data.get("From", "unknown")
    to_number    = form_data.get("To", "unknown")
    direction    = form_data.get("Direction", "unknown")

    logger.info(f"Call connected — UUID={call_uuid}, From={from_number}, To={to_number}, Direction={direction}")
    return Response(content="OK", status_code=200)


@app.post("/hangup")
async def hangup_call(request: Request):
    """Vobiz calls this when the call ends."""
    form_data = await request.form()
    call_uuid    = form_data.get("CallUUID", "unknown")
    duration     = form_data.get("Duration", "0")
    hangup_cause = form_data.get("HangupCause", "unknown")

    logger.info(f"Call ended — UUID={call_uuid}, Duration={duration}s, Cause={hangup_cause}")
    return Response(content="OK", status_code=200)


@app.post("/stream-status")
async def stream_status(request: Request):
    """Vobiz sends stream lifecycle events here."""
    form_data = await request.form()
    event     = form_data.get("Event", "unknown")
    stream_id = form_data.get("StreamID", "unknown")
    call_uuid = form_data.get("CallUUID", "unknown")

    logger.info(f"Stream event — Event={event}, StreamID={stream_id}, CallUUID={call_uuid}")
    return Response(content="OK", status_code=200)


@app.get("/health")
async def health_check():
    """Health check — returns server status and current public URL."""
    return {"status": "healthy", "url": NGROK_URL}


# ---------------------------------------------------------------------------
# ngrok Tunnel
# ---------------------------------------------------------------------------

def setup_ngrok():
    """Create a public ngrok tunnel pointing to this server."""
    global NGROK_URL

    if NGROK_AUTH_TOKEN:
        conf.get_default().auth_token = NGROK_AUTH_TOKEN

    tunnel = ngrok.connect(addr=str(HTTP_PORT), proto="http")
    NGROK_URL = tunnel.public_url

    if NGROK_URL.startswith("http://"):
        NGROK_URL = NGROK_URL.replace("http://", "https://")

    logger.info("=" * 60)
    logger.info("ngrok tunnel established!")
    logger.info(f"  Public URL: {NGROK_URL}")
    logger.info(f"  API docs:   {NGROK_URL}/docs")
    logger.info("  Use this URL as LOCAL_BASE_URL in your .env")
    logger.info("  so the XML answer_urls point to this public address.")
    logger.info("=" * 60)

    return NGROK_URL


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    global NGROK_URL

    logger.info("Starting Vobiz Stream Application Builder...")

    if NGROK_AUTH_TOKEN:
        try:
            setup_ngrok()
        except Exception as e:
            logger.error(f"ngrok failed: {e}")
            sys.exit(1)
    else:
        NGROK_URL = f"http://localhost:{HTTP_PORT}"
        logger.info("=" * 60)
        logger.info("LOCAL MODE — no ngrok, no S3 required.")
        logger.info(f"  API:      http://localhost:{HTTP_PORT}")
        logger.info(f"  UI:       open index.html in your browser")
        logger.info(f"  API docs: http://localhost:{HTTP_PORT}/docs")
        logger.info("=" * 60)

    logger.info(f"Starting HTTP server on port {HTTP_PORT}...")
    uvicorn.run(app, host="0.0.0.0", port=HTTP_PORT, log_level="warning")


if __name__ == "__main__":
    main()
